require "user.options"
require "user.colorscheme"
require "user.plugins"
require "user.whichkey"
require "user.keymaps"
-- requires v0.8.0 require "user.nvim-tree"
--require "user.cmp"
--require "user.lsp"
--require "user.dap"
--require "user.telescope"
--require "user.gitsigns"
--require "user.treesitter"
--require "user.comment"
--require "user.toggleterm"
--require "user.indentblankline"
--require "user.autocommands"
--require "user.symbols-outline"

--vim.lsp.set_log_level("debug")
