vim.g.loaded_netrw = 1 -- use nvimtree instead
vim.g.loaded_netrwPlugin = 1
vim.opt.swapfile = false
vim.opt.number = true
vim.opt.tabstop = 4
vim.opt.expandtab =  true
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.shiftround = true
vim.opt.textwidth = 0
vim.opt.wrap = false
vim.opt.list = true
vim.opt.listchars = "trail:·,tab:»-"
vim.opt.mouse = ""
vim.opt.encoding = "utf-8"
vim.opt.incsearch = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.startofline = false
vim.opt.termguicolors = true
vim.opt.numberwidth = 4                         -- set number column width to 2 {default 4}
vim.opt.signcolumn = "yes"                      -- always show the sign column, otherwise it would shift the text each time
vim.opt.undofile=true                           -- persistent undo
vim.opt.timeoutlen=400                          -- faster whichkey window
vim.opt.background="light"
